flaskweb/app/main/__init__.py
# -*- coding=utf-8 -*-
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

flaskweb/app/main/views.py
# -*- coding=utf-8 -*-

from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user, login_user, logout_user
import jinja2

from ..models import *
from .. import db
from . import main


@main.route('/', methods=['GET', 'POST'])
def index():
    
    # print("#"*40)
    # for i in Transaction.Transaction.query.all():
    #     print(i.usage)
    # print("#"*40)
    a = Transaction.Transaction.query.all()
    if current_user.is_authenticated:
        try:
            user = User.User.get_user_by_id(current_user.get_id())
            a = user.transaction

        except :
            flash(u"None user")
            return redirect(url_for('main.index'))
        
    print("#"*40)
    for i in CompanyBill.CompanyBill.query.all():
        print(i.date)
    print("#"*40)

    return render_template('main/index.html', list=a)
    # template_env = jinja2.Environment(loader=jinja2.FileSystemLoader('template'))
    # template_env.get_template('base.html')
    # return template_env.render()


@main.route('/read/', methods=['GET', 'POST'])
def read():
    a = request.args.get('trans')       # runturn an unicode
    print("TRANSACTION IN MAIN.ROUTE")
    
    a = Transaction.Transaction.get_transaction_by_id(int(a))
    print(a)
    if a is not None:
        return render_template('main/read.html', a = a)
    flash(u'未找到相关文章')
    return redirect(url_for('main.index'))

flaskweb/app/templates/main/index.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="col-md-8">
    
        {% for foo in list %}
            <div class="act">
                <h3><a href="{{ url_for('main.read' , trans=foo.id) }}">{{ foo.user_name }}</a></h3>

                <br>{{foo.usage}}
            </div>
        {% endfor %}
    </div>
{% endblock %}

flaskweb/app/templates/main/read.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="container">
        <div class="col-md-12">
        <h1>details</h1>
        
            <table class="table">
                <thead>
                <tr>
                    <th>clerk ID: </th>
                    <th>equipment ID: </th>
                    <th>Date: </th>
                    <th>Usage: </th>
                    <th>operation </th>
                </tr>
                </thead>
                <tbody>
                
                    <tr>
                        <td>{{ a.clerk_id }}</td>
                        <th>{{ a.equipment.id }}</th>
                        <th>{{ (a.date|string)[5:10] }}</th>
                        <th>{{ a.usage }}</th>
                        {% if current_user.is_authenticated %}
                        <td><a href="{{ url_for('admin.transaction_modify',id=a.id) }}">pay</a></td>
                        {% endif %}
                    </tr>
               
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}